### ISSUE TITLE
Button Hover effect

### ISSUE THREAD

**Issue by Lensco825** [Lensco825/Newspaper#2]
Add a hover effect for the buttons you make.

**Comment by supsa-ak** [comment]
Hi, I want to contribute on this issue. I am participating in Hacktoberfest.

**Comment by Lensco825** [comment]
You may and thanks for contributing!

**Comment by Lensco825** [comment]
@supsa-ak  I've already added the hover effect, however, you can help with stylizing and adding articles to the newspaper by making pull requests!

**Comment by supsa-ak** [comment]
Just consider my commit. The hovering effect is very better.
