### ISSUE TITLE
Theme Changer

### ISSUE THREAD

**Issue by Lensco825** [Lensco825/Newspaper#3]
Have a button that changes the theme of the newsletter. We can use this by having a button that uses `classList.togge()` and toggle classes with different themes.

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue, I also noticed that the website overflows on the horizontal axis, I would like to fix it so everything stays inside the body container. :)

**Comment by Lensco825** [comment]
Anyone's allowed to help and thanks for noticing that overflow!

**Comment by Lensco825** [comment]
@abitsalihu I've already added the theme changer, but it doesn't work so well. It doesn't fully cover the webpage which I'm guessing is because the body doesn't fully cover the Html element. We also need to stylize the color of the li elements. You can help me with this at any time!

**Comment by abitsalihu** [comment]
@Lensco825 I will work on this tomorrow, I'll try and fix the overflowing problem swell as whatever I see that need's a bit of fixing. :)
